### ISSUE TITLE
redis-rb 4.8.0 compatibility issues

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_api#105]
redis-rb v4.8.0 introduced some changes that generate some deprecation messages in the log files

https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#480

> Deprecate sadd and srem returning a boolean when called with a single argument. To enable the redis 5.0 behavior you can set Redis.sadd_returns_boolean = false.

This results in log entries:

```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/sparql-client-fb4a89b420f8/lib/sparql/client.rb:450:in `block in query_put_cache')
```
and 
```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /srv/ontoportal/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-4f9139d870c3/lib/ontologies_linked_data/http_cache/cacheable_resource.rb:159:in `cache_write')
```

**Comment by alexskr** [comment]
resolved by https://github.com/ncbo/ontologies_api/pull/120
