### ISSUE TITLE
redis-store gem update from v1.9.1 -> 1.9.2 causes 'cache error: unknown keywords: :scheme, :namespace, :raw' in logs

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_api#119]
When redis-store gem is updated from v1.9.1 -> v1.9.2 unit test pass and when code is deployed to staging env API seem to work; however, we see `cache error: unknown keywords: :scheme, :namespace, :raw` log entries for every API hit.  

```log
cache error: unknown keywords: :scheme, :namespace, :raw
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-client-0.14.1/lib/redis_client/config.rb:21:in `initialize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-client-0.14.1/lib/redis_client/config.rb:184:in `initialize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-client-0.14.1/lib/redis_client.rb:143:in `new'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-client-0.14.1/lib/redis_client.rb:143:in `config'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-5.0.6/lib/redis/client.rb:23:in `config'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-5.0.6/lib/redis.rb:157:in `initialize_client'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-5.0.6/lib/redis.rb:73:in `initialize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-store-1.9.2/lib/redis/store.rb:17:in `initialize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:26:in `new'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:26:in `create'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:9:in `create'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-rack-cache-2.2.1/lib/rack/cache/redis_base.rb:25:in `initialize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-rack-cache-2.2.1/lib/rack/cache/redis_base.rb:20:in `new'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/redis-rack-cache-2.2.1/lib/rack/cache/redis_base.rb:20:in `resolve'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/storage.rb:39:in `create_store'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/storage.rb:18:in `resolve_metastore_uri'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:35:in `metastore'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:176:in `lookup'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:67:in `call!'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:52:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-attack-6.6.1/lib/rack/attack.rb:110:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-13bb138aa40c/lib/ontologies_linked_data/security/access_denied_middleware.rb:10:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-13bb138aa40c/lib/ontologies_linked_data/security/authorization.rb:45:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/releases/20230724163041/lib/rack/param_translator.rb:47:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/rack-post-body-to-params-0fd30e710386/lib/rack/post-body-to-params.rb:144:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-accept-0.4.5/lib/rack/accept/context.rb:22:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/releases/20230724163041/lib/rack/slice_detection.rb:35:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/static.rb:124:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/commonlogger.rb:33:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/logger.rb:15:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/commonlogger.rb:33:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/methodoverride.rb:22:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.3.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:634:in `process_client'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:739:in `worker_loop'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:143:in `start'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bin/unicorn:23:in `load'
/srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bin/unicorn:23:in `<top (required)>'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli.rb:491:in `exec'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/cli.rb:28:in `start'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/exe/bundle:45:in `block in <top (required)>'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.0/exe/bundle:33:in `<top (required)>'
/usr/local/rbenv/versions/2.7.8/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.7.8/bin/bundle:23:in `<main>'
```

redis-store gem v1.9.2 has a compatibility issue with redis-rb gem 5.0 which should resolve when redis-store PR  
[redis-store PR#359](https://github.com/redis-store/redis-store/pull/359) gets merged.

**Comment by alexskr** [comment]
resolved by https://github.com/ncbo/ontologies_api/pull/120
