### ISSUE TITLE
Annotator: NoMethodError - undefined method `prefLabel' for #<#<Class:0x0000558de0a7a558>:0x0000558dd75b00f8>:

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_api#154]
I am seeing a number of errors generated by annotator calls:
```
2024-07-22 02:11:40 - NoMethodError - undefined method `prefLabel' for #<#<Class:0x0000558de0a7a558>:0x0000558dd75b00f8>:
        /srv/ontoportal/ontologies_api/releases/20240718174655/helpers/search_helper.rb:360:in `block in populate_classes_from_search'
        /srv/ontoportal/ontologies_api/releases/20240718174655/helpers/search_helper.rb:348:in `each'
        /srv/ontoportal/ontologies_api/releases/20240718174655/helpers/search_helper.rb:348:in `populate_classes_from_search'
        /srv/ontoportal/ontologies_api/releases/20240718174655/controllers/annotator_controller.rb:90:in `process_annotation'
        /srv/ontoportal/ontologies_api/releases/20240718174655/controllers/annotator_controller.rb:16:in `block (2 levels) in <class:AnnotatorController>'
```

This error started to appear after the API v5.30.1 release

**Comment by syphax-bouazzouni** [comment]
this https://github.com/ncbo/ontologies_api/pull/155 may fix that, I applied the fix that did @mdorf for the search to the annotator also, as the annotator uses the indexed data to populate the classes attributes (because it is more efficient than calling the triple store)
