### ISSUE TITLE
Broken wildcard search with two terms

### ISSUE THREAD

**Issue by heikkimu** [ncbo/ontologies_api#39]
Greetings, 

I couldn't find more appropriate place for bug reporting, but this is really a show stopper for us.

When trying to do an search with two terms and asterisk server kindly shows me response 500. Without asterisk the result is not really usable.

Any ideas how to solve this? This seems to be working in versions 2.2 and 2.5, but not in 2.4.

I've tried updating the ontologies_api to latest 4.x-version, with no success in circumventing this bug.

We're having NCBO Virtual Appliance v2.4
https://www.bioontology.org/wiki/index.php/Category:NCBO_Virtual_Appliance

Query:
```
http://10.10.10.200:8080/search?q=Adrenal+car*&ontologies=SNOMEDCT&objecttypes=class&include=prefLabel&display_links=no&no_context=true&pagesize=10&apikey=apikey
```

Server error from unicorn.stderr.log:
```
Error: 'field "synonymSuggestNgram"      (term=adrenal)','trace'=>'java.lang.IllegalStateException: field "synonymSuggestNgram" was indexed without position data; cannot run PhraseQuery (term=adrenal)

URI: http://localhost:8082/solr/core1/select?wt=ruby
Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"}
Request Data: "objecttypes=class&include=prefLabel&display_links=no&no_context=true&pagesize=10&&display=prefLabel&defType=edismax&stopwords=true&lowercaseOperators=true&fl=*%2Cscore&hl=on&hl.simple.pre=%3Cem%3E&hl.simple.post=%3C%2Fem%3E&qt=%2Fsuggest_ncbo&qf=prefLabelExact%5E100+prefLabelSuggestEdge%5E50+synonymSuggestEdge%5E10+prefLabelSuggestNgram+synonymSuggestNgram+resource_id+notation+cui+semanticType+ontologyType&pf=prefLabelSuggest%5E50&hl.fl=prefLabelExact+prefLabelSuggestEdge+synonymSuggestEdge+prefLabelSuggestNgram+synonymSuggestNgram+resource_id+notation+cui+semanticType+ontologyType&fq=submissionAcronym%3A%22SNOMEDCT%22+AND+obsolete%3Afalse+AND+-provisional%3Atrue&page=1&start=0&rows=10&q=%22Adrenal%5C+corti%22"

Backtrace: /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `post'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bundler/gems/goo-c8cc22b62c09/lib/goo/search/search.rb:43:in `search'
/srv/ncbo/ontologies_api/current/controllers/search_controller.rb:26:in `process_search'
/srv/ncbo/ontologies_api/current/controllers/search_controller.rb:8:in `block (2 levels) in <class:SearchController>'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
/srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!':
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
    (eval):2:in `post'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bundler/gems/goo-c8cc22b62c09/lib/goo/search/search.rb:43:in `search'
    /srv/ncbo/ontologies_api/current/controllers/search_controller.rb:26:in `process_search'
    /srv/ncbo/ontologies_api/current/controllers/search_controller.rb:8:in `block (2 levels) in <class:SearchController>'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/sinatra.rb:139:in `route_eval_with_newrelic'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/sinatra.rb:119:in `process_route_with_newrelic'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/sinatra.rb:164:in `dispatch_and_notice_errors_with_newrelic'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/sinatra.rb:150:in `block in dispatch_with_newrelic'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/sinatra.rb:147:in `dispatch_with_newrelic'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249:in `fetch'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189:in `lookup'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66:in `call!'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bundler/gems/ontologies_linked_data-5985b89b7b60/lib/ontologies_linked_data/security/access_denied_middleware.rb:10:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bundler/gems/ontologies_linked_data-5985b89b7b60/lib/ontologies_linked_data/security/authorization.rb:45:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/lib/rack/param_translator.rb:47:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bundler/gems/rack-post-body-to-params-0fd30e710386/lib/rack/post-body-to-params.rb:144:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-accept-0.4.5/lib/rack/accept/context.rb:22:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/lib/rack/slice_detection.rb:35:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.3.323/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:52:in `process_client'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
    /srv/ncbo/ontologies_api/current/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
```

**Comment by heikkimu** [comment]
It seems than when escaping spaces to underscores, it can perform searches, but still won't be able to cope terms with special characters, like comma.

`search?q=Adrenal+car*` -> `search?q=Adrenal_car*`

`Lymphoma,_large_B-cell` won't find anything

**Comment by mdorf** [comment]
What happens if you add "suggest=true" parameter instead of the asterisk? Ex:

http://data.bioontology.org/search?q=Adrenal+car&suggest=true&ontologies=SNOMEDCT&objecttypes=class&include=prefLabel&display_links=no&no_context=true&pagesize=10

Are you still getting the same error?

**Comment by heikkimu** [comment]
Yep, asteriks or suggest=true

**Comment by heikkimu** [comment]
Any ideas how to proceed?

**Comment by ncbo-deployer** [comment]
Hello Heikki,

I am hoping the list may have a contribution here. I’m guessing that this is a bug, one that may take some time to fix.

The BioPortal support team is on holiday for the Thanksgiving weekend, so in any case it will be at least Monday before we have any further info.

Sorry I don’t have more positive news.

John

________________________________

**Comment by heikkimu** [comment]
No worries,

I can also fix some stuff, if it's not too complicated. I'm not really good with ruby.

It seems that it is fixed in newer version.

Can we just install Version 2.5 without virtual appliance and how production ready that is?

https://www.bioontology.org/wiki/index.php/BioPortal_Virtual_Appliance_Release_Notes

**Comment by graybeal** [comment]
> Can we just install Version 2.5 without virtual appliance

I'm not sure what you mean, install Version 2.5 *of what* without the virtual appliance?

> and how production ready that is?

Release Candidate 3 of Virtual Appliance 2.5 is stable and largely complete. It is lacking a few refinements, features, and bug fixes (there are *always* a few more bug fixes :->), but we are not aware of any fundamental issues in installation or operation.
