### ISSUE TITLE
Search fails occasionally with valueset_exclude_roots=true

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_api#41]
Per @marcosmro report, the following queries failed repeatedly in the past:

Class search: http://data.bioontology.org/search?q=disease&also_search_provisional=true&valueset_exclude_roots=true&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true

Value set search: http://data.bioontology.org/search?q=delivery+procedures&also_search_provisional=true&ontology_types=VALUE_SET_COLLECTION&valueset_roots_only=true&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true 

The issue is NOT reproducible in the local environment. Clearing caches has not resolved the issue either. The production log shows the following error:
```shell
2018-01-22 06:30:40 - NoMethodError - undefined method `id' for nil:NilClass:
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:369:in `block in model_load_sliced'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:368:in `each'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:368:in `model_load_sliced'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:266:in `block in model_load'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:261:in `each'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:261:in `each_slice'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/sparql/queries.rb:261:in `model_load'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/base/where.rb:214:in `process_query_intl'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/goo-5e7c8f42ed25/lib/goo/base/where.rb:131:in `process_query'
        ...
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-1146741a5f84/lib/ontologies_linked_data/models/ontology_submission.rb:1414:in `roots'
	/srv/ncbo/ontologies_api/releases/20171221012214/helpers/search_helper.rb:246:in `block in get_valueset_root_ids'
```
This refers to the following block of code in ncbo/goo:
```ruby
        models_by_id = {}
        if models
          ids = []
          models.each do |m|
            ids << m.id
            models_by_id[m.id] = m
          end
        elsif ids
          ids.each do |id|
            models_by_id[id] = klass_struct ? klass_struct.new : klass.new
            models_by_id[id].klass = klass if klass_struct
            models_by_id[id].id = id
          end
        else #a where without models

        end
```

**Comment by mdorf** [comment]
Added code to goo to ignore NULL models.
