### ISSUE TITLE
/users/create_reset_password_token endpoint throws 500 internal server error

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_api#42]
Received a report from an end user that they are unable to use the [lost password page](https://bioportal.bioontology.org/lost_pass) in the BioPortal UI to get a password reminder. The problem appears to be at the REST level. The call to the /users/create_reset_password_token REST URL results in a 500 error. This isn't reproducible in the staging UI, only production. The production REST log doesn't show any stack trace, only the 500 status, e.g.:

```
172.20.222.51 - ncbobioportal [06/Feb/2018:10:58:53 -0800] "POST /users/create_reset_password_token HTTP/1.0" 500 30 0.1105
```

**Comment by jvendetti** [comment]
Partial stack trace from local dev environment:

```
NoMethodError: undefined method `body' for Pony:Module
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pony-1.11/lib/pony.rb:250:in `block in build_mail'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:155:in `initialize'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/mail.rb:51:in `new'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/mail.rb:51:in `new'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pony-1.11/lib/pony.rb:215:in `build_mail'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pony-1.11/lib/pony.rb:166:in `mail'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-1146741a5f84/lib/ontologies_linked_data/utils/notifications.rb:24:in `notify'
	/Users/jvendetti/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-1146741a5f84/lib/ontologies_linked_data/utils/notifications.rb:118:in `reset_password'
	/Users/jvendetti/Development/GitHub/ncbo/ontologies_api/controllers/users_controller.rb:35:in `block (2 levels) in <class:UsersController>'
```

This was produced by running the UI and ontologies_api locally, pointing to production data.

**Comment by jvendetti** [comment]
Fixed in this commit: https://github.com/ncbo/ontologies_linked_data/commit/cca6f01a22d879b3ff8204ba6a2b1b03e4d3f720.
