### ISSUE TITLE
Views endpoint fails when custom ontology set includes ontologies with views

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_api#47]
Steps to reproduce:

1. Via the [BioPortal user interface](https://bioportal.bioontology.org/), navigate to the Account Settings page for any account.
2. In the "Custom Ontology Set" section, select an ontology that has associated views, e.g., [NCIT](https://bioportal.bioontology.org/ontologies/NCIT).
3. Click the "Save Custom Ontologies" button.
4. Issue the following REST API call in a browser: http://data.bioontology.org/ontologies/NCIT/views.

Note that the resulting 500 error only occurs for ontology objects with values in the views attribute. Ontology objects with no views don't fail in this way.

Stack trace from local dev environment:

```
RuntimeError: can't modify frozen Array
  /Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/users_helper.rb:15:in `delete_if'
  /Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/users_helper.rb:15:in `filter_for_user_onts'
  /Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/application_helper.rb:130:in `reply'
  /Users/jvendetti/Development/GitHub/ncbo/ontologies_api/controllers/views_controller.rb:11:in `block (2 levels) in <class:ViewsController>'
```

**Comment by xindiguo** [comment]
Hi, 
our project cannot move forward due to this bug. Can you give me a rough timeline on when this can be fixed? 
Thank you in advance.

**Comment by jvendetti** [comment]
Hi @xindiguo. Are you able to give more specifics about what you're doing and why this issue is preventing your project from moving forward? We may be able to propose a temporary workarounds until this issue is addressed / released to our production environment.

**Comment by ncbo-deployer** [comment]
Xindi, wouldn't it work to create a new account (that doesn't have the special ontology list selected) and connect your REDCap database to that? 

I'm not intimately familiar with REDCap setup, so I'm not sure why you have chosen to have a custom ontology set. I'm pretty sure REDCap does not require that. Perhaps you send send your question about how to make your setup work first to the REDCap support team, and if they identify a problem in the way the interface talks to BioPortal, they can contact us about possible alternatives.

**Comment by xindiguo** [comment]
Hi @ncbo-deployer, REDCap only needs the account API key from the BioPortal and the ontologies from the custom list can be used in REDCap. 

I have tried to add custom ontology set in my new account and an error page showed up when I was trying to save it. (screenshot attached)

<img width="528" alt="screen shot 2018-05-15 at 11 03 34 am" src="https://user-images.githubusercontent.com/16565812/40075018-1c8813bc-5830-11e8-85cf-955c60696b3d.png">

<img width="1426" alt="screen shot 2018-05-15 at 11 03 42 am" src="https://user-images.githubusercontent.com/16565812/40075034-25320644-5830-11e8-9b77-203279e4182d.png">
